[tool.poetry]
name = "codingtestr"
version = "0.1.0"
description = ""
authors = ["geunhoPang <<>>"]

[tool.poetry.dependencies]
python = "^3.8"
more-itertools = "^8.12.0"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
