// 최댓값 구하기 (역순 정렬 후 최상단 가져오기)
SELECT DATETIME FROM ANIMAL_INS ORDER BY DATETIME DESC LIMIT 1

// 최솟값 구하기 (정렬 후 최상단 가져오기)
SELECT DATETIME FROM ANIMAL_INS ORDER BY DATETIME ASC LIMIT 1

// COUNT 함수 (특정 COLUMN의 갯수 구하기)
SELECT COUNT(*) FROM ANIMAL_INS

// COUNT 함수(DISTINCT를 이용한 중복 제외 카운트)
SELECT COUNT(DISTINCT NAME) FROM ANIMAL_INS

